name: Node.js CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Node.js server with PM2
        run: /home/ubuntu/.nvm/versions/node/v20.11.1/bin/pm2 start /home/ubuntu/actions-runner/_work/sample-nodejs/sample-nodejs/node.js
